version: '3.8'

services:
  light-bot:
    build: .
    container_name: light-bot
    restart: unless-stopped
    ports:
      - "${FLASK_PORT:-5000}:5000"
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHANNEL_ID=${TELEGRAM_CHANNEL_ID}
      - FLASK_PORT=5000
      - API_TOKEN=${API_TOKEN}
      - POWER_STATUS_FILE=/data/power_status.txt
      - LAST_STATUS_FILE=/data/last_status.txt
    volumes:
      - power-data:/data
    env_file:
      - .env

volumes:
  power-data:
    driver: local
