version: '3.8'

services:
  light-bot:
    build: .
    container_name: light-bot
    restart: unless-stopped
    ports:
      - "${FLASK_PORT:-5000}:5000"
    environment:
      # Telegram configuration
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHANNEL_ID=${TELEGRAM_CHANNEL_ID}
      - TELEGRAM_SCHEDULE_CHANNEL_ID=${TELEGRAM_SCHEDULE_CHANNEL_ID}
      # DO NOT set TELEGRAM_API_BASE_URL in production (only for E2E testing)

      # Server configuration
      - FLASK_PORT=5000
      - API_TOKEN=${API_TOKEN}
      - POWER_STATUS_FILE=/data/power_status.txt
      - LAST_STATUS_FILE=/data/last_status.txt

      # Timezone and schedule configuration
      - TIMEZONE=${TIMEZONE:-Europe/Kyiv}
      - YASNO_GROUP=${YASNO_GROUP:-2.1}
      - YASNO_CITY=${YASNO_CITY:-kiev}
      # DO NOT set YASNO_API_BASE_URL in production (only for E2E testing)

      # Schedule check intervals
      - SCHEDULE_CHECK_INTERVAL=${SCHEDULE_CHECK_INTERVAL:-3600}
      - SCHEDULE_EVENING_HOUR=${SCHEDULE_EVENING_HOUR:-20}
      - SCHEDULE_EVENING_MINUTE=${SCHEDULE_EVENING_MINUTE:-0}
      - SCHEDULE_CHANGES_START_HOUR=${SCHEDULE_CHANGES_START_HOUR:-8}
      - SCHEDULE_TOMORROW_START_HOUR=${SCHEDULE_TOMORROW_START_HOUR:-18}
    volumes:
      - power-data:/data
    env_file:
      - .env

volumes:
  power-data:
    driver: local
